version: 2

sources:
  - name: raw_data_circle
    description: raw data circle sportwear dataset
    tables:
      - name: raw_cc_stock
        description: stock of product
      - name: raw_cc_sales
        description: sales of product
        tests:
          - unique:
              column_name: "(product_id || '-' || date_date )"

models:
  - name: stg_raw_data_circle__raw_cc_stock
    description: cleaning raw stock
    tests:
      - unique:
          column_name: product_id
  - name: stg_raw_data_circle__raw_cc_sales
    description: cleaning raw sales

